# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-25 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BmiRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmiRecords', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='DiabeteRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabeteRecords', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='DietRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietRecords', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluateResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluateResults', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurementReminder', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicineReminder', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SportsReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sportsRemainder', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('realname', models.CharField(max_length=50)),
                ('phoneNum', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('waistlineProfile', models.CharField(max_length=50)),
                ('weightProfile', models.CharField(max_length=50)),
                ('heightProfile', models.CharField(max_length=50)),
                ('bmiProfile', models.CharField(max_length=50)),
                ('relativesSituation', models.CharField(max_length=50)),
                ('meatSituation', models.CharField(max_length=50)),
                ('fruitSituation', models.CharField(max_length=50)),
                ('bloodPressure', models.CharField(max_length=50)),
                ('cholesterol', models.CharField(max_length=50)),
                ('triglyceride', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='sportsreminder',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.User'),
        ),
        migrations.AddField(
            model_name='medicinereminder',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.User'),
        ),
        migrations.AddField(
            model_name='measurementreminder',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.User'),
        ),
        migrations.AddField(
            model_name='evaluateresults',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.User'),
        ),
        migrations.AddField(
            model_name='dietrecords',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.User'),
        ),
        migrations.AddField(
            model_name='diabeterecords',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.User'),
        ),
        migrations.AddField(
            model_name='bmirecords',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.User'),
        ),
    ]
