# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='admin_ip',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
