# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-06 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_admin_admin_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='check_num',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='publish_num',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
